config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
require 'open-uri'

class ArticlesController < ApplicationController

  before_action :set_article, only: %i[show edit update destroy]
  before_action :upload_image, only: %i[update]
  after_action :upload_image, only: %i[create]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def upload_image
    if params[:image_url]&.present?
      UploadArticleImageJob.perform_later(params[:image_url], @article)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def self.upload_image(image_url, article)
    image = open(image_url)
    file_name = "article_#{article.id}"
    article.image.attach(io: image, filename: file_name)
  end
end

app/views/articles/_article.html.slim
div[class="article"]
  h2[class="article-title"] = article.title
  = link_to t(".view"), article_path(article), class: "view-article"
  br
  = link_to t(".edit"), edit_article_path(article), data: { test: "edit-article-#{article.id}" }
  br
  = link_to t(".delete"), article_path(article),
                          method: :delete,
                          class: "delete-article",
                          data: { cofirm: t(".confirm?"), test: "delete-article-#{article.id}" }
  hr

app/views/articles/_form.html.slim
= f.input :title, input_html: { data: { test: "article-title" } }
= f.input :image_url, as: :fake, input_html: { data: { test: "article-image-url" } }
= f.input :body, as: :text, input_html: { data: { test: "article-body" } }

app/views/articles/edit.html.slim
= simple_form_for @article, url: article_path, metdhod: :put do |f|
  = render "form", f: f
  = f.submit(data: { test: "update-article" })

= link_to t(".back"), article_path(@article)

app/views/articles/index.html.slim
p = link_to t(".new"), new_article_path, data: { test: "create-new-article" }

= render @articles

app/views/articles/new.html.slim
= simple_form_for @article, url: articles_path do |f|
  = render "form", f: f
  = f.submit(data: { test: "create-article" })

app/views/articles/show.html.slim
h1 = @article.title
- if @article.image.attached?
  = image_tag @article.image
p = @article.body
= link_to t(".back"), articles_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>